-- MySQL Script generated by MySQL Workbench
-- Mon May 19 22:46:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_g4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_g4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_g4` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_g4` ;

-- -----------------------------------------------------
-- Table `db_g4`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_g4`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_g4`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_g4`.`alumno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nro_documento` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_alumno_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_g4`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_g4`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_g4`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_g4`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_g4`.`empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `area` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `pais` VARCHAR(50) NOT NULL,
  `salario` DECIMAL(7,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_g4`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_g4`.`matricula` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alumno_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `alumno_id` (`alumno_id` ASC) VISIBLE,
  INDEX `curso_id` (`curso_id` ASC) VISIBLE,
  CONSTRAINT `matricula_ibfk_1`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db_g4`.`alumno` (`id`),
  CONSTRAINT `matricula_ibfk_2`
    FOREIGN KEY (`curso_id`)
    REFERENCES `db_g4`.`curso` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
