-- SENTENCIAS DDL
-- CREAMOS UNA TABLA PARA ALMACENAR LOS ALUMNOS DE APP TKALUMNOS
CREATE TABLE alumno(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    celular VARCHAR(50) NULL
);

-- MODIFICAR UNA TABLA
ALTER TABLE alumno
ADD COLUMN nota INT DEFAULT 0;

ALTER TABLE alumno
DROP COLUMN nota;

DROP TABLE alumno;
